language: go

go:
    - 1.4.2

addons:
    postgresql: "9.3"

before_script:
    - psql -C 'create database testdb;' -U postgres

env:
    - DBUSER=postgres
    - DBHOST=localhost

install: make deps

script: make ci
