language: go

go:
    - 1.4.2

addons:
    postgresql: "9.3"

before_script:
    - psql -c 'create database testdb;' -U postgres

env:
    - DBUSER=postgres DBPASS=test BA_USER=test BA_PASS=test TEMPLATE_DIR=./templates STATIC_DIR=./static

install: make deps

script: make ci

notifications:
    email:
        recipients:
            - nkhumphreys@gmail.com
        on_success: always
        on_failure: always
